esphome:
  name: influxdb-writer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Cipolatti"
  password: "XXXXXX"
  manual_ip:
    static_ip: 192.168.1.50
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Influxdb-Writer Fallback Hotspot"
    password: "E61qJH92LTrc"

captive_portal:

#http_request:
#  id: http_client
#  useragent: esphome/device
#  verify_ssl: false

#interval:
#  - interval: 600s
#    then:
#      - http_request.post:
#          id: http_client
#          url: http://192.168.1.14:8086/api/v2/write?org=Noone&bucket=TestBucket&precision=s
#          headers: 
#            Authorization: "Token TeleAuUi9M9hiQXCouzLvRIUFEW6PqHraoba51ivt7ux0Ve11QMk7ti9nlJafkOmZiUhzH_Jl484xhAJN1ExYw=="       
#            Content-Type: "text/plain; charset=utf-8"
#          body: "temperature,sensor=bathroom,device=DesktopPC,city=Sunchales value=100"

http_request:
  id: http_client
  verify_ssl: false

influxdb_writer:
  id: writer
  host: "192.168.1.14"
  token: "TeleAuUi9M9hiQXCouzLvRIUFEW6PqHraoba51ivt7ux0Ve11QMk7ti9nlJafkOmZiUhzH_Jl484xhAJN1ExYw=="
  bucket: "TestBucket"
  org: "Noone"
  http_request_id: http_client

    